### ISSUE TITLE
ERROR: Gray not defined

### ISSUE THREAD

**Issue by dchun** [dfdx/FaceDatasets.jl#1]
After running the sample script: "multi.jl" in the ActiveAppearanceModel package, I get a few warnings and errors:

```
Warning: could not import Base.Text into Tk
WARNING: Color is deprecated, please use Colors instead. See https://github.com/JuliaGraphics/Colors.jl
ERROR: Gray not defined
```

From the following file:

```
ActiveAppearanceModels/examples/multi.jl, in expression starting on line 4
```

Which is referenced from:

```
FaceDatasets/src/FaceDatasets.jl, in expression starting on line 6
```

Which is referenced from:

```
FaceDatasets/src/core.jl, in expression starting on line 5
```

Which contains the following line:

``` julia
Base.convert{T}(::Type{Matrix{Float64}}, img::Image{Gray{T}}) = convert(Array{Float64, 2}, convert(Array, img))
```

I tried modifying the dependency on the deprecated package Color to Colors but that didn't seem to fix the error.

Any idea what the issue might be?

**Comment by dfdx** [comment]
Yes, I know this issue and am exactly at the time of translating some of my projects to Julia 0.4 and latest state of Colors.jl / Images.jl,  so you can expect resolution in a couple of days (since you depend on it, I'll try to speed up things). 

For reference: what version of Julia are you using?

**Comment by dchun** [comment]
Cool. I'm currently on v0.3.11

**Comment by dfdx** [comment]
Try to update both - FaceDatasets.jl and ActiveAppearanceModels.jl - to the latest master and let me know if you still have any issues.

**Comment by dchun** [comment]
That fixes the error. Thanks!
